### ISSUE TITLE
Rpm install on cent os 7 fail.

### ISSUE THREAD

**Issue by AI-PaaS** [projectcalico/calico-mesos-deployments#14]
I followed the https://github.com/projectcalico/calico-mesos-deployments/blob/master/docs/RpmInstallCalicoMesos.md to install the calico-mesos. the new rpm download address is point to 0.27, after i downloaded the tar and yum install, i found that the docker 1.8 is required by theses rpms like before. I uninstall the latest docker and installed these rpms.

when i  start the calico-mesos,  the lib so in the module.json is put in wrong place //opt/net-modules/. 
I correct it and the calico-mesos service can run.

but when i run the mesos-slave, the following error occured:

Mar 02 20:45:09 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:09.936592 25057 logging.cpp:188] INFO level logging started!
Mar 02 20:45:09 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:09.937135 25057 main.cpp:211] Build: 2016-02-16 19:28:49 by
Mar 02 20:45:09 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:09.937150 25057 main.cpp:213] Version: 0.27.0
Mar 02 20:45:10 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:10.045433 25057 containerizer.cpp:143] Using isolation: com_mesosphere_mesos_NetworkIsolator,filesystem/posix
Mar 02 20:45:10 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:10.053779 25057 linux_launcher.cpp:101] Using /sys/fs/cgroup/freezer as the freezer hierarchy for the Linux launcher
Mar 02 20:45:10 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:10.060516 25057 systemd.cpp:126] systemd version `219` detected
Mar 02 20:45:10 host-10-1-235-199 systemd[1]: Created slice Mesos Executors Slice.
Mar 02 20:45:10 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:10.071303 25057 systemd.cpp:208] Started systemd slice `mesos_executors.slice`
Mar 02 20:45:10 host-10-1-235-199 mesos-slave[25076]: I0302 20:45:10.073199 25057 network_isolator.cpp:489] Loading Network Isolator module
Mar 02 20:45:10 host-10-1-235-199 mesos-slave[25076]: Failed to create a master detector: Expecting a (chroot) path for ZooKeeper ('/' is not supported)
Mar 02 20:45:10 host-10-1-235-199 systemd[1]: mesos-slave.service: main process exited, code=exited, status=1/FAILURE
Mar 02 20:45:10 host-10-1-235-199 systemd[1]: Unit mesos-slave.service entered failed state.
Mar 02 20:45:10 host-10-1-235-199 systemd[1]: mesos-slave.service failed.
^C

**Comment by djosborne** [comment]
Hey @AI-PaaS thanks for the feedback.

> i found that the docker 1.8 is required by theses rpms like before. 

You're right, seems we missed the docker dependency in the core mesos/netmodules RPMs. I've raised a [PR#106](https://github.com/mesosphere/net-modules/pull/106) to resolve it

>`Mar 02 20:45:10 host-10-1-235-199 mesos-slave[25076]: Failed to create a master detector: Expecting a (chroot) path for ZooKeeper ('/' is not supported)`

Can you paste your `/etc/default/mesos-slave`? I suspect your `MASTER` variable may have a typo

> the lib so in the module.json is put in wrong place //opt/net-modules/

Thanks for letting us know, I'll look at getting this typo fixed asap

**Comment by AI-PaaS** [comment]
[root@host-10-1-235-199 default]# more mesos-slave
MASTER=zk://10.1.235.197:2181
ETCD_AUTHORITY=10.1.235.197:2379

**Comment by AI-PaaS** [comment]
Thanks for reply. It's my mistake. I should set the file like this: MASTER=zk://10.1.235.197:2181/mesos

**Comment by djosborne** [comment]
Great, I just [updated our RPM doc](https://github.com/projectcalico/calico-mesos-deployments/commit/78e465fa326e04b48c4a965ea3004bb7d662d775) to specify that you need `/mesos` at the end of your `MASTER=zk://` variable 

Additionally, [PR 107](https://github.com/mesosphere/net-modules/pull/107) will fix the docker dependency, as well as moving the `netmodules.so` to `/usr/lib64/mesos/libmesos_network_isolator.so`. Once that PR is merged and the `.so` is in its new location, #16 can be merged which updates `modules.json`

I'll close this issue once 16 and 107 are in, as that covers everything raised here.

**Comment by djosborne** [comment]
@AI-PaaS We've cut a new release which includes RPMs with fixes for the issues you've raised here: https://github.com/projectcalico/calico-mesos-deployments/releases/tag/0.27.0%2B2
