### ISSUE TITLE
Vagrant provisioning failing to download calico-mesos.rpm and netmodules rpm

### ISSUE THREAD

**Issue by Lax77** [projectcalico/calico-mesos-deployments#19]
Vagrant provisioning (vagrant up) is failing on the Agent, cant seem to download from the URLs listed in Vagrantfile. Were the URLs obsolete?

Here are the URLs that are failing for me,
mesos_netmodules_rpm_url = "https://github.com/projectcalico/calico-mesos-deployments/releases/download/0.27.1%2B1/mesos-netmodules-rpms.tar"

calico_mesos_rpm_url = "https://github.com/projectcalico/calico-mesos-deployments/releases/download/0.27.1%2B2/calico-mesos.rpm"

**Comment by djosborne** [comment]
Please use a stable release for the Vagrant demo: https://github.com/projectcalico/calico-mesos-deployments/releases/tag/0.27.0%2B1

We've made significant changes to the Vagrant demo recently which won't be stable until our next release

**Comment by djosborne** [comment]
Actually, we are going to work to cut a pre-release today that will include the linked RPMs and tars. I'd recommend holding off for that if you can :smile:

**Comment by Lax77** [comment]
Ok :), thanks for the heads up. 

I did try this version of vagrant too (https://github.com/projectcalico/calico-mesos-deployments/blob/0.27.0%2B1/Vagrantfile) by pulling in the source version of the 0.27 zip file. Though provision completes, on the agent instance I am seeing '**calico-node container not running**' issue.

**Comment by djosborne** [comment]
@Lax77 We've cut a new release: https://github.com/projectcalico/calico-mesos-deployments/releases/tag/0.27.0%2B2

Mostly in an effort to get working RPMs and Vagrant scripts up. We're pushing docs improvements to the next release, so don't hesitate [contact us on Slack](https://calicousers-slackin.herokuapp.com/) with any questions in the meantime

**Comment by Lax77** [comment]
Sure will do, Thanks.
