### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by spirrello** [projectcalico/calico-mesos-deployments#38]
Hi,

The following link within your guide is broken.  Any chance you can take a look at this next week to have it corrected?  Thanks.

https://github.com/projectcalico/calico-mesos-deployments/blob/master/docs/CalicoWithTheDockerContainerizer.md

**Comment by djosborne** [comment]
Apologies @spirrello 
We're working towards merging a docs rework branch ASAP. The information you are looking for is on it:
https://github.com/projectcalico/calico-mesos-deployments/blob/docs-rework/docs/mesos/UsageGuideDockerContainerizer.md

**Comment by djosborne** [comment]
@spirrello Our docs rework is complete - we've moved the guide you're looking for to calico-containers:

- https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/ManualInstallCalicoDockerContainerizer.md
- https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/UsageGuideDockerContainerizer.md

**Comment by spirrello** [comment]
Very cool thanks a ton.  I'm very impressed with Calico so far but Etcd is
a pain to work with.  Do you know if it works with Consul or Zookeeper by
chance?

**Comment by djosborne** [comment]
We've focused on supporting etcd as the backend, as it has met all of Calico's requirements and does a great job keeping up with Calico's scale and speed. We have not yet ported to any other backends. 

We are very open to feedback, as supporting other backends is something we've always planned, but just haven't had a strong push from the community to do so yet - what about etcd makes it a pain point for you?

**Comment by spirrello** [comment]
Just getting it up and running.  I can get the cluster initiated via exec
etcd followed by the respective parameters but if I use the "etcd.conf"
file it goes into a blackhole with the following error on all cluster
nodes.  I have an open issue with the Etcd team in Github but I'm waiting
for a solid fix.

"etcd rafthttp: request sent was ignored (cluster ID mismatch: remote"
